
SOURCES = main.cpp were_surface.cpp were_widget.cpp were_painter.cpp were_button.cpp
HEADERS = were_surface.h were_widget.h were_painter.h were_button.h

all: test

test: ${SOURCES} ${HEADERS}
	g++ -o test ${SOURCES} -I../were/include



