#ifndef SPARKLE_PROTOCOL_H
#define SPARKLE_PROTOCOL_H

#define SPARKLE_CLIENT_REGISTER_SURFACE_FILE    0x00
#define SPARKLE_CLIENT_UNREGISTER_SURFACE       0x01
#define SPARKLE_CLIENT_SET_SURFACE_POSITION     0x02
#define SPARKLE_CLIENT_ADD_SURFACE_DAMAGE       0x03

#define SPARKLE_SERVER_DISPLAY_SIZE             0x00
#define SPARKLE_SERVER_POINTER_DOWN             0x01
#define SPARKLE_SERVER_POINTER_UP               0x02
#define SPARKLE_SERVER_POINTER_MOTION           0x03
#define SPARKLE_SERVER_KEY_DOWN                 0x04
#define SPARKLE_SERVER_KEY_UP                   0x05

#endif //SPARKLE_PROTOCOL_H

